import type { TerminalTheme } from "../engine/index.js";

export const flowCliDarkTheme: TerminalTheme = {
  name: "Flow CLI Dark",
  roles: {
    markdownText: { foreground: "white" },
    markdownMarkup: { foreground: "brightBlack", dim: true },
    markdownHeading1: { foreground: "brightCyan", bold: true },
    markdownHeading2: { foreground: "cyan", bold: true },
    markdownHeading3: { foreground: "brightBlue", bold: true },
    markdownHeading4: { foreground: "blue", bold: true },
    markdownHeading5: { foreground: "brightMagenta", bold: true },
    markdownHeading6: { foreground: "magenta", bold: true },
    markdownEmphasis: { foreground: "brightMagenta", italic: true },
    markdownStrong: { foreground: "brightWhite", bold: true },
    markdownUnderline: { foreground: "brightCyan", underline: true },
    markdownDeleted: { foreground: "brightBlack", strikethrough: true },
    markdownHighlight: { foreground: "black", background: "brightYellow" },
    markdownCode: {
      foreground: "brightGreen",
      background: "brightBlack",
    },
    markdownCodeMarkup: {
      foreground: "brightBlack",
      background: "brightBlack",
      dim: true,
    },
    "codeSyntax.attribute": { foreground: "brightYellow" },
    "codeSyntax.builtIn": { foreground: "cyan" },
    "codeSyntax.comment": { foreground: "brightBlack", dim: true, italic: true },
    "codeSyntax.function": { foreground: "brightBlue" },
    "codeSyntax.keyword": { foreground: "brightMagenta", bold: true },
    "codeSyntax.literal": { foreground: "brightCyan" },
    "codeSyntax.meta": { foreground: "magenta" },
    "codeSyntax.number": { foreground: "brightCyan" },
    "codeSyntax.operator": { foreground: "white" },
    "codeSyntax.params": { foreground: "white" },
    "codeSyntax.property": { foreground: "cyan" },
    "codeSyntax.regexp": { foreground: "brightRed" },
    "codeSyntax.string": { foreground: "brightGreen" },
    "codeSyntax.symbol": { foreground: "brightMagenta" },
    "codeSyntax.text": { foreground: "white" },
    "codeSyntax.type": { foreground: "brightYellow" },
    "codeSyntax.variable": { foreground: "brightCyan" },
    markdownLink: { foreground: "brightBlue", underline: true },
    markdownImage: { foreground: "brightMagenta", bold: true },
    "markdownImage.loading": { foreground: "brightBlack", dim: true },
    "markdownImage.unavailable": { foreground: "brightBlack" },
    "markdownImage.error": { foreground: "brightRed" },
    markdownListMarker: { foreground: "brightCyan", bold: true },
    markdownQuoteMarker: {
      foreground: "brightCyan",
      background: "brightBlack",
      bold: true,
    },
    markdownQuote: {
      foreground: "white",
      background: "brightBlack",
      italic: true,
    },
    markdownSeparator: { foreground: "brightBlack", dim: true },
    placeholder: { foreground: "brightBlack", dim: true },
    currentSentence: { background: "brightBlack" },
    searchMatch: { underline: true },
    searchMatchActive: { foreground: "black", background: "brightYellow" },
    textHighlight: { background: "brightBlack" },
    lint: { foreground: "brightRed", underline: true },
    focusInactive: { foreground: "brightBlack", dim: true },
    codeBlockLabel: { foreground: "brightBlack", dim: true },
    tableBorder: { foreground: "brightBlack", dim: true },
    tableHeader: { foreground: "brightWhite", bold: true },
    tableCell: { foreground: "white" },
    taskChecked: { foreground: "brightGreen" },
    taskUnchecked: { foreground: "brightBlack" },
    selection: { inverse: true },
  },
};
